# Generated by Django 3.2.16 on 2022-11-14 10:12

from django.db import migrations, models
import studentapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, validators=[studentapp.validators.gmail_validation])),
                ('content', models.TextField()),
            ],
        ),
    ]
