# Generated by Django 3.2.16 on 2022-11-14 11:35

from django.db import migrations, models
import studentapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_alter_contact_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=100, null=True, validators=[studentapp.validators.gmail_validation])),
                ('age', models.IntegerField(null=True)),
                ('claass', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=200, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
